services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: bahasakita-app-dev
    restart: unless-stopped
    volumes:
      # Sinkronkan semuanya KECUALI direktori vendor
      - .:/var/www/html
      - vendor_data:/var/www/html/vendor
    ports:
      - "5173:5173" # Port untuk Vite Hot Reloading
    networks:
      - caddy_net_external

  db:
    image: mysql:8.0
    container_name: bahasakita-db-dev
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: a_very_strong_and_different_root_password
    volumes:
      - mysql-data-dev:/var/lib/mysql
    networks:
      - caddy_net_external

networks:
  caddy_net_external:
    external: true
    name: caddy_net

volumes:
  mysql-data-dev:
  # Tambahkan named volume untuk vendor
  vendor_data: