FROM php:8.3-fpm-alpine

# Install system dependencies, including Node.js and npm
RUN apk add --no-cache \
    curl \
    libzip-dev \
    zip \
    unzip \
    libpng-dev \
    libjpeg-turbo-dev \
    freetype-dev \
    icu-dev \
    nodejs \
    npm

# Install PHP extensions
RUN docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install -j$(nproc) gd pdo_mysql zip bcmath exif intl

# Install Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

WORKDIR /var/www/html

# Copy application files
COPY . .

# Install Composer dependencies
RUN composer install

# Install NPM dependencies
RUN npm install

EXPOSE 9000
EXPOSE 5173

# Jalankan npm run dev dan php-fpm
CMD ["/bin/sh", "-c", "npm run dev & php-fpm"]